// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_ZAq8x1RaZgVCMnG3ZIgKBN9SA46_VE',
    appId: '1:979367591574:web:e27f46af1d1cbeb9c58cb7',
    messagingSenderId: '979367591574',
    projectId: 'cavz-project',
    authDomain: 'cavz-project.firebaseapp.com',
    storageBucket: 'cavz-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKFFJVMUnYyy1aRFw5AP0lFmLLCs-Y0I',
    appId: '1:979367591574:android:45bedfb4a55003f5c58cb7',
    messagingSenderId: '979367591574',
    projectId: 'cavz-project',
    storageBucket: 'cavz-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZA9EpVVDLtRfU_cDAgiX80TxYyHC85U',
    appId: '1:979367591574:ios:655fa0040d1121e2c58cb7',
    messagingSenderId: '979367591574',
    projectId: 'cavz-project',
    storageBucket: 'cavz-project.appspot.com',
    iosBundleId: 'com.example.taskCavz',
  );
}
